@startuml

hide footbox
title Telavox Alice calls Bob on TDC

actor       "alice"                                   order 1
participant "sip proxy"    as sipproxy                order 2
participant "sip server 1" as sip1                    order 3
participant "tlb"                                     order 4
participant "tdc proxy 1"  as tdcproxy1 << gateway >> order 6
participant "bob@tdc"      as tdcnet                  order 7

alice -> sipproxy : INVITE sip:bob@tdc, From: alice
sipproxy -> alice : 100 Trying

sipproxy -> tlb : where is alice?
tlb -> sipproxy : can be found on SIP server 1

sipproxy -> sip1 : INVITE sip:bob@tdc, From: alice
sip1 -> sipproxy : 100 Trying

sip1 -> tlb : where is bob?
tlb -> sip1 : can be found on TDC proxy 1

sip1 -> tdcproxy1 : INVITE sip:bob@tdc, From: alice
tdcproxy1 -> sip1 : 100 Trying

tdcproxy1 -> tdcnet : INVITE sip:bob@tdc, From: alice

tdcnet -> tdcproxy1 : 180 Ringing
note right: Bob's phone is ringing
tdcproxy1 -> sip1   : 180 Ringing
sip1 -> sipproxy    : 180 Ringing
sipproxy -> alice   : 180 Ringing

tdcnet -> tdcproxy1 : 200 OK
note right: Bob answers the call
tdcproxy1 -> sip1   : 200 OK
sip1 -> sipproxy    : 200 OK
sipproxy -> alice   : 200 OK

alice -> sipproxy   : ACK
sipproxy -> sip1    : ACK
sip1 -> tdcproxy1   : ACK
tdcproxy1 -> tdcnet : ACK

loop until hungup
    alice -[#0000FF]> sip1  : RTP
    sip1 -[#0000FF]> tdcnet : RTP
    tdcnet -[#0000FF]> sip1 : RTP
    sip1 -[#0000FF]> alice  : RTP
end

alice -> sipproxy   : BYE
note right: Alice hangs up the call
sipproxy -> sip1    : BYE
sip1 -> tdcproxy1   : BYE
tdcproxy1 -> tdcnet : BYE

tdcnet -> tdcproxy1 : 200 OK
tdcproxy1 -> sip1   : 200 OK
sip1 -> sipproxy    : 200 OK
sipproxy -> alice   : 200 OK

@enduml