#!/usr/bin/env bash

LEVEL=$1

echo "Flashing $FPC_PLATFORM_TARGET..."

cd out/target/"$FPC_PLATFORM_TARGET"
pwd

unzip -o target.zip

if [ "$LEVEL" == "all" ]; then
    fastboot flash boot boot.img
    fastboot flash cache cache.img
    fastboot flash recovery recovery.img
    fastboot flash system system.img
    fastboot flash userdata userdata.img
else
    fastboot flash system system.img
fi

fastboot reboot
